# Generated by Django 5.2.12 on 2026-05-11 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antrian', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueticket',
            name='customer_photo',
            field=models.TextField(blank=True, null=True, verbose_name='Foto Pelanggan (Base64)'),
        ),
    ]
