# Generated by Django 5.2.12 on 2026-05-11 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antrian', '0002_queueticket_customer_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queueticket',
            name='customer_photo',
        ),
        migrations.CreateModel(
            name='DummyResi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resi_number', models.CharField(max_length=20, unique=True, verbose_name='Nomor Resi')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Nama Pelanggan')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='No HP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Masuk')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='antrian.servicetype', verbose_name='Jenis Layanan')),
            ],
            options={
                'verbose_name': 'Resi Paket',
                'verbose_name_plural': 'Resi Paket',
                'ordering': ['-created_at'],
            },
        ),
    ]
